import { jsonResponse as json } from '../_shared/auth.ts'

const BANKS = [
  { code: '01', name: 'Kenya Commercial Bank' },
  { code: '02', name: 'Standard Chartered Bank' },
  { code: '03', name: 'Barclays Bank (ABSA)' },
  { code: '07', name: 'Commercial Bank of Africa' },
  { code: '10', name: 'Prime Bank' },
  { code: '11', name: 'Co-operative Bank' },
  { code: '12', name: 'National Bank of Kenya' },
  { code: '14', name: 'Oriental Commercial Bank' },
  { code: '16', name: 'Citibank' },
  { code: '17', name: 'Habib Bank AG Zurich' },
  { code: '18', name: 'Middle East Bank' },
  { code: '19', name: 'Bank of Africa' },
  { code: '23', name: 'Consolidated Bank' },
  { code: '25', name: 'Credit Bank' },
  { code: '26', name: 'Trans-National Bank' },
  { code: '30', name: 'Chase Bank (in receivership)' },
  { code: '31', name: 'Stanbic Bank' },
  { code: '35', name: 'African Banking Corporation' },
  { code: '49', name: 'Equity Bank' },
  { code: '50', name: 'Family Bank' },
  { code: '51', name: 'Gulf African Bank' },
  { code: '53', name: 'Guaranty Trust Bank' },
  { code: '54', name: 'Victoria Commercial Bank' },
  { code: '55', name: 'Guardian Bank' },
  { code: '57', name: 'I&M Bank' },
  { code: '61', name: 'HFC Bank' },
  { code: '63', name: 'Diamond Trust Bank' },
  { code: '66', name: 'SBM Bank' },
  { code: '68', name: 'Equity Bank (formerly Finserve)' },
  { code: '70', name: 'Ecobank' },
  { code: '72', name: 'Gulf African Bank' },
  { code: '74', name: 'Faulu Microfinance Bank' },
  { code: '76', name: 'M-Oriental Bank' },
  { code: '78', name: 'NCBA Bank' },
]

Deno.serve(() => json({ banks: BANKS }))
